services:
  taxi-database:
    image: postgres:15
    environment:
      - POSTGRES_USER=de_user_pg
      - POSTGRES_PASSWORD=de_pas_pg
      - POSTGRES_DB=taxi_db
    volumes:
      - ./ny_taxi_postgres_data:/var/lib/postgresql/data:rw 
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "8080:80"  